### ISSUE TITLE
How to label the Mix CLIPS form FSD-MIX-SED?

### ISSUE THREAD

**Issue by chester-w-xie** [wangyu/rethink-audio-fsl#15]
"To label a clip, we consider all sound events within the 1s window. If an event overlaps with the window for more than 0.5s or half of the event duration, we add the corresponding class into the clip label. We then consider the number of classes within a clip as the
level of polyphony with the assumption that it is rare to have short non-overlapping events within a 1s window. "

Can you provide a demo?  Thank you very much!

**Comment by wangyu** [comment]
Added a demo function that does the labeling: 
https://github.com/wangyu/rethink-audio-fsl/blob/6e9626efc0fddadfe2f032e18d1794066a08c8b1/data/utils.py#L8
